[package]
name = "dsc"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.10", features = ["derive"] }
quick-xml = {version = "0.28.1", features = ["serialize", "serde"] }
quickxml_to_serde = "0.5.0"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
serde_yaml = "0.9.21"
toml = "0.7.3"


[profile.release]
lto = true
panic = "abort"
codegen-units = 1
strip = true

