[package]
name = "dsc"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.10", features = ["derive"] }
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
serde_yaml = "0.9.19"
toml = "0.7.3"


[profile.release]
lto = true
panic = "abort"
codegen-units = 1
strip = true

